apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: ObjectStore
metadata:
  name: objectstore-sample
spec:
  # Add fields here
  config:
    mountFrom:
      secretKeyRef:
        name: s3-bucket
        key: object-store.yaml
