
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: objectstores.monitoring.banzaicloud.io
spec:
  group: monitoring.banzaicloud.io
  names:
    kind: ObjectStore
    listKind: ObjectStoreList
    plural: objectstores
    singular: objectstore
  scope: ""
  validation:
    openAPIV3Schema:
      description: ObjectStore is the Schema for the objectstores API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ObjectStoreSpec defines the desired state of ObjectStore
          properties:
            bucket:
              type: object
            compactor:
              type: object
            config:
              description: Config
              properties:
                mountFrom:
                  properties:
                    secretKeyRef:
                      properties:
                        key:
                          description: Secret key for the value
                          type: string
                        name:
                          description: Name of the kubernetes secret
                          type: string
                      required:
                      - key
                      - name
                      type: object
                  type: object
                value:
                  type: string
                valueFrom:
                  properties:
                    secretKeyRef:
                      properties:
                        key:
                          description: Secret key for the value
                          type: string
                        name:
                          description: Name of the kubernetes secret
                          type: string
                      required:
                      - key
                      - name
                      type: object
                  type: object
              type: object
          required:
          - config
          type: object
        status:
          description: ObjectStoreStatus defines the observed state of ObjectStore
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
